# Site settings
title: The Major League Hacking Hackathon Organizer's Guide
email: hi@mlh.io
description: > # this means to ignore newlines until "baseurl:"
  The Book of Hackathon is an open-source initiative to make a hackathon playbook.
  Follow the playbook and it will walk you through every step of throwing a great hackathon.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://guide.mlh.io" # the base hostname & protocol for your site
twitter_username: mlhacks
github_username:  mlh

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
markdown: kramdown
